### PR TITLE
some fixes and instance drops & coffers supplements

### PR DESCRIPTION
**Pull request by ClayLivince**
Greetings! Here is some work.
Three things in this pull request.

1. added some fishing spots (two diadem and some out-sea-fishing spots) and missing icons for treasure hunting (The Dungeons of Lyhe Ghiah and etc.)

2. a tool method to get HD icons in game. (such as 80x80 item icons etc., using the EnsureEntryHQ method with the same argument of EnsureEntry in IconDatabase)

3. use the supplemental data scraped from the lodestone to fill the drops and coffers in 5.0 dungeons and raids which no longer provided by libra eorzea. and you can use the script to get all instances' coffer and drops, but there will be no mob data with it, but it's quite enough for now for these instances. I am trying to find another data source of bnpcs.
the script (main.py) will be at \GarlandTools\Supplemental\Utils\ folder, you can use pycharm or something else IDE to build and run it.
here is how to use the script:
  - install the requirements
  - open main.py and be sure to config the LOAD_LOCAL to false: This is a option to load instance list generated by last scrap.
  - run the script.
  - after it's done, check the fails.json to see if there were any failed to fetch things. if no,
  - copy the FFXIV Data - Duties.json to the \GarlandTools\Supplemental\ folder.
  - run the garland build with modified things.

### CODE REVIEW

**Comment by ClayLivince** [comment]
The commit has a list of scraped instances included. so simply rebuild the garland project and try run it before doing python things can be less stressed. I am very sorry for the bad English spelling and vocabulary as I am still learning English. orz

**Comment by Supamiu** [comment]
Hi, thank you for this PR 😃 

It would have been better to have the lodestone parsing baked inside the C# part but I guess it'd be a bit too hard to implement, and the script doesn't need to be run too often so it's fine.

I'll run the importer with your additions soon 👍

**Review by Supamiu — APPROVED** [review]

**Comment by Supamiu** [comment]
As a side note, you might want to contribute your lodestone CSS selection research in the https://github.com/xivapi/lodestone-css-selectors project, where CSS selectors for lodestone are maintained and curated for various libraries to use 🚀

**Comment by ClayLivince** [comment]
Sure, I also think it is better to make that as a submodule. working on these things.

**Comment by ClayLivince** [comment]
Extracted repo was here. https://github.com/ClayLivince/FFXIV-Lodestone-Duty-Scraper
I am new in github and I am very sorry for troubling.

**Pull request merged**
